apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: nightmare-project
type: Opaque
stringData:
  jwt-secret: "mebn-task-manager-2024-certificate"
  admin-password: "admin123"
