apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: nightmare-project
type: Opaque
stringData:
  mongodb-root-password: "secretpassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: nightmare-project
type: Opaque
stringData:
  jwt-secret: "mern-task-manager-super-secret-key-2024"