apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mebn-internal-policy
  namespace: nightmare-project
spec:
  podSelector:
    matchLabels:
      project: mebn-task-manager
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          project: mebn-task-manager
  egress:
  - to:
    - podSelector:
        matchLabels:
          project: mebn-task-manager
