apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mebn-task-manager
  namespace: nightmare-project
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: mebn-task-manager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend  # ← ClusterIP сервис
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend   # ← ClusterIP сервис
            port:
              number: 5000
