apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: webapp-demo
type: Opaque
data:
  # Пароль для MongoDB: password123 (закодирован в base64)
  mongodb-password: cGFzc3dvcmQxMjM=
  mongodb-root-password: cm9vdHBhc3N3b3Jk