apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
  namespace: webapp-demo
type: Opaque
data:
  mongodb-uri: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGI6MjcwMTcvdGFza3NkYj9hdXRoU291cmNlPWFkbWlu
